config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  # get  '/signup',  to:   new_user_registration_path 
  resources :users
  resources :alls
  resources :ipurchase
  resources :buitem
  resources :nitems
 get  '/home',    to: 'nitems#home'
 get  '/add_item',    to: 'nitems#add_item'

#  get "/add_item", to: "newitem#new"
end

app/models/all.rb
class All < ApplicationRecord
end

app/models/allproduct.rb
class Allproduct < ApplicationRecord
end

app/models/buitem.rb
class Buitem < ApplicationRecord
  belongs_to :user
end

app/models/citem.rb
class Citem < ApplicationRecord
end

app/models/ipurchase.rb
class Ipurchase < ApplicationRecord
  belongs_to :user
end

app/models/myitem.rb
class Myitem < ApplicationRecord
end

app/models/myproduct.rb
class Myproduct < ApplicationRecord
  #belongs_to :user
end

app/models/nitem.rb
class Nitem < ApplicationRecord
  belongs_to :user
   validates :price,  presence: true, :numericality => { :greater_than_or_equal_to => 0 }, length: { maximum: 20}
end

app/models/pitem.rb
class Pitem < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify

end

app/models/uitem.rb
class Uitem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
    #has_many :mypoducts, dependent: :destroy
    has_many :ipurchases, dependent: :destroy
    has_many :buitems, dependent: :destroy
    has_many :nitems, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/all_helper.rb
module AllHelper
end

app/helpers/buitem_helper.rb
module BuitemHelper
end

app/helpers/ipurchase_helper.rb
module IpurchaseHelper
end

app/helpers/newitem_helper.rb
module NewitemHelper
end

app/helpers/nitems_helper.rb
module NitemsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a>"MARKETING APP"</a>
  </small>
    <ul>
      <li><%= link_to "help", help_path %></li>  
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
         </li>

        <% else %>
          <li>
            <%= link_to('LOGIN', new_user_session_path)  %>  
          </li>
        <% end %>
        <% unless current_user.nil? %>
          <% if current_user.has_role? :admin %>
            <li>
              <%= link_to('SELLING',buitem_index_path) %> 
           </li>
          <% else %>
            <li> <%= link_to('All Product',  alls_path )  %>  </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              New Product <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
             <li> <%= link_to('Add Items', nitems_path )  %>  </li>
             <li> <%= link_to('Your Added Items',add_item_path) %></li>
            </ul>
            </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Items <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <li><%= link_to('My Cart',ipurchase_index_path)  %></li>
             <li> <%= link_to('Purchased',buitem_index_path)  %>  </li>
             
            </ul>
          </li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body style="background-image:url('<%= asset_path('text.jpg') %>')">
  	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @xx.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@xx.errors.count, "error") %>.
    </div>
    <ul>
    <% @xx.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>